/**
 * Action types template.
 */
export const REQUEST_GET_SOMETHING = 'REQUEST_GET_SOMETHING';
export const SUCCESS_GET_SOMETHING = 'SUCCESS_GET_SOMETHING';
export const FAILURE_GET_SOMETHING = 'FAILURE_GET_SOMETHING';

export const SET_CURRENT_ROUTE_NAME = 'SET_CURRENT_ROUTE_NAME';
